### ISSUE TITLE
AppVeyor fails to locate the artifacts

### ISSUE THREAD

**Issue by xorz57** [xorz57/chalk#1]
https://github.com/xorz57/chalk/blob/65cdaf72083a4fe92e0a17187d64950c4d012143/appveyor.yml#L18

AppVeyor fails to locate the artifacts. A solution to this problem is to use cpack inside build_script instead.

```yaml
version: '{build}'
image: Ubuntu
environment:
  matrix:
  - FLAG: OFF
  - FLAG: ON
build_script:
- sh: >-
    mkdir build

    cd build

    cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=$FLAG

    make

    cpack
test: off
artifacts:
- path: build/*.gz
- path: build/*.Z
deploy:
- provider: GitHub
  auth_token:
    secure: AtDbVKW82I4iP+STKQ9ZEHEjzZZDYN/GqxC4mPfejyDyKs8Nozo3gYEHVLJUaZup
  force_update: true
  on:
    APPVEYOR_REPO_TAG: true
```
